name: Build and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with Docker
        run: |
          docker build --target artifacts -t portfolio-build .
          container_id=$(docker create portfolio-build)
          mkdir -p ./gh-pages-deploy
          docker cp $container_id:/ ./gh-pages-deploy
          docker rm $container_id
          touch ./gh-pages-deploy/.nojekyll

          # Create a 404.html that redirects to index.html for SPA routing
          cp ./gh-pages-deploy/index.html ./gh-pages-deploy/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages-deploy
          branch: gh-pages
